import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className="antialiased h-auto w-full bg-light-background dark:bg-dark-background"
      >
        {children}
      </body>
    </html>
  );
}
